Allow retrieving device information
joaobarbosa/onesignal-python pull request #1
Opened 2017-03-23 13:17 UTC by dolohow

2017-05-24 12:26 UTC, joaobarbosa commented
Hi @dolohow, sorry for the late response! I've been busy in the last few days.
Would you mind checking the build status? :)

2017-06-12 09:16 UTC, dolohow commented
How about now? :)

2017-06-12 13:06 UTC, joaobarbosa requested changes

2017-06-12 13:06 UTC, joaobarbosa commented on onesignalclient/user_client.py
> +        endpoint = 'players/%s?%s' % (player_id, app_id)
In this case, we need to send the param itself together - `app_id` needs to be something like `app_id=sampleappid`. I think it would be better to handle it inside the function, and not outside. Like an `if` to check if `app_id` is set, and then, add it to the endpoint. 👍 

You can check how the [app_client][1] works, we could do this the same way :)

[1]: https://github.com/joaobarbosa/onesignal-python/blob/master/onesignalclient/app_client.py

2018-03-07 17:07 UTC, joaobarbosa commented
Hi @dolohow, are you still going to support this PR? 😄

2018-05-11 07:39 UTC, dolohow commented
I left the company that was interested in pushing this forward.   I would close this PR.

2018-05-11 07:39 UTC, closed without merging